## 创建tensor

In [1]:
import torch
import numpy as np
torch.manual_seed(1)

### 直接创建

### 通过torch.tensor创建张量

In [2]:
arr = np.ones((3, 3))
print("ndarray的数据类型：", arr.dtype)

t = torch.tensor(arr, device='cuda')
# t = torch.tensor(arr)

print(t)

ndarray的数据类型： float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)


### 通过torch.from_numpy创建张量

In [5]:
#torch.from_numpy 与原ndarray共享内存
arr = np.array([[1, 2, 3], [4, 5, 6]])
t = torch.from_numpy(arr)
print("numpy array: ", arr)
print("tensor : ", t)

print("\n修改arr")
arr[0, 0] = 0
print("numpy array: ", arr)
print("tensor : ", t)

print("\n修改tensor")
t[0, 0] = -1
print("numpy array: ", arr)
print("tensor : ", t)

numpy array:  [[1 2 3]
 [4 5 6]]
tensor :  tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

修改arr
numpy array:  [[0 2 3]
 [4 5 6]]
tensor :  tensor([[0, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

修改tensor
numpy array:  [[-1  2  3]
 [ 4  5  6]]
tensor :  tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)


## 依据数值创建

### 通过torch.zeros创建张量

In [6]:
out_t = torch.tensor([1])
t = torch.zeros((3, 3), out=out_t)

print(t, '\n', out_t)
print(id(t), id(out_t), id(t) == id(out_t))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
2987155259048 2987155259048 True


### 通过torch.full创建全1张量 （奇奇怪怪）

In [7]:
t = torch.full((3, 3), 1)
print(t)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


..\aten\src\ATen\native\TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


### 通过torch.arange创建等差数列张量

In [11]:
t = torch.arange(2, 10, 2)
print(t)

tensor([2, 4, 6, 8])


### 通过torch.linspace创建均分数列张量

In [2]:
# step(步长)=(end-start)/(steps-1)
# 即 (10-2)/(5-1)
#t = torch.linspace(2, 10, 5)
t = torch.linspace(2, 10, 6)
print(t)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


## 依概率分布创建张量

### 通过torch.normal创建正态分布张量

In [3]:
# mean：张量 std: 张量
# t_normal[1]是从mean=2，std=2的分布中采用得到的
mean = torch.arange(1, 5, dtype=torch.float)
std = torch.arange(1, 5, dtype=torch.float)
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)
print("t_normal[1]: ", t_normal[1])

mean:tensor([1., 2., 3., 4.])
std:tensor([1., 2., 3., 4.])
tensor([1.6614, 2.5338, 3.1850, 6.4853])
t_normal[1]:  tensor(2.5338)


In [17]:
# mean：标量 std: 标量
# 两个都为标量时，要增加size参数
t_normal = torch.normal(0., 1., size=(4,))
print(t_normal)

tensor([-1.1024,  1.4788,  2.0622, -0.8935])


In [3]:
# mean：张量 std: 标量
mean = torch.arange(1, 5, dtype=torch.float)
std = 1
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:1
tensor([1.6614, 2.2669, 3.0617, 4.6213])


### torch.randn() 

从标准正态分布（均值为0，方差为1，即高斯白噪声）中抽取的一组随机数

### torch.rand_like() [0,1]上均匀分布

### torch.randint() 均匀整数分布

### torch.randperm() 生成0到n-1的随机排列

In [23]:
t = torch.randperm(8)
print(t) #常用来生成乱序索引

tensor([4, 6, 2, 5, 7, 1, 3, 0])


### torch.bernoulli() 伯努利分布