## 张量的操作

In [1]:
import torch
torch.manual_seed(1)

## 张量的拼接与切分

### torch.cat()

- tensors 张量序列
- dim 要拼接的维度

In [3]:
t = torch.ones((2, 3))
print("t: ",t)
t_0 = torch.cat([t, t], dim=0)
t_1 = torch.cat([t, t, t], dim=1)

print("t_0:{} shape:{}\nt_1:{} shape:{}".format(
    t_0, t_0.shape, t_1, t_1.shape))

t:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
t_0:tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) shape:torch.Size([4, 3])
t_1:tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]) shape:torch.Size([2, 9])


### torch.stack()

- 在新创建的维度dim上进行拼接

In [7]:
# dim=0 (2,3)往后移
t = torch.ones((2, 3))
t_stack = torch.stack([t, t, t], dim=0)

print("\nt_stack:{}\n shape:{}".format(t_stack, t_stack.shape))


t_stack:tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
 shape:torch.Size([3, 2, 3])


### torch.chunk()

- chunks： 要切分的份数
- dim: 要切分的维度

将张量按维度dim进行平均切分  
返回值: 张量列表  
若不能整除，最后一份张量小于其他张量

In [9]:
a = torch.ones((2, 7))  # 7
list_of_tensors = torch.chunk(a, dim=1, chunks=3)   # 3,3,1

for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}, shape is {}".format(idx+1, t, t.shape))

第1个张量：tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第2个张量：tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第3个张量：tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])


### torch.split

In [12]:
t = torch.ones((2, 5))

list_of_tensors = torch.split(t, [2, 1, 2], dim=1)  
    # [2, 1, 1]报错， 2+1+2=5，维度需一致
for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}, shape is {}".format(idx+1, t, t.shape))

第1个张量：tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])
第2个张量：tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])
第3个张量：tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])


### torch.index_select

In [4]:
t = torch.randint(0, 9, size=(3, 3))
idx = torch.tensor([0, 2], dtype=torch.long)# float, idx:  tensor([0, 2])

t_select = torch.index_select(t, dim=0, index=idx) #dim=0按行，选idx[0,2]行，再拼接
print("t:\n{}\nt_select:\n{}".format(t, t_select))

t:
tensor([[2, 7, 6],
        [6, 8, 7],
        [6, 0, 7]])
t_select:
tensor([[2, 7, 6],
        [6, 0, 7]])


### torch.masked_select

- mask与input同形状的布尔类型张量

In [17]:
t = torch.randint(0, 9, size=(3, 3))
mask = t.le(5)  # ge is mean greater than or equal/   gt: greater than  le  lt
t_select = torch.masked_select(t, mask)
print("t:\n{}\nmask:\n{}\nt_select:\n{} ".format(t, mask, t_select))

t:
tensor([[4, 7, 5],
        [0, 7, 1],
        [4, 6, 1]])
mask:
tensor([[ True, False,  True],
        [ True, False,  True],
        [ True, False,  True]])
t_select:
tensor([4, 5, 0, 1, 4, 1]) 


## 张量变换

### torch.reshape() ：变换张量形状

当张量在内存中是连续的，新张量与input共享数据内存

In [19]:
t = torch.randperm(8)
t_reshape = torch.reshape(t, (-1, 2, 2))    # -1
print("t:{}\nt_reshape:\n{}".format(t, t_reshape))

t[0] = 1024
print("t:{}\nt_reshape:\n{}".format(t, t_reshape))
print("t.data 内存地址:{}".format(id(t.data)))
print("t_reshape.data 内存地址:{}".format(id(t_reshape.data)))

t:tensor([5, 6, 3, 1, 0, 2, 4, 7])
t_reshape:
tensor([[[5, 6],
         [3, 1]],

        [[0, 2],
         [4, 7]]])
t:tensor([1024,    6,    3,    1,    0,    2,    4,    7])
t_reshape:
tensor([[[1024,    6],
         [   3,    1]],

        [[   0,    2],
         [   4,    7]]])
t.data 内存地址:1860703597016
t_reshape.data 内存地址:1860703597016


### torch.transpose() :  变换张量的两个维度

这里其实略复杂，见[其他笔记](https://blog.csdn.net/u012762410/article/details/78912667)

In [20]:
t = torch.rand((2, 3, 4))
t_transpose = torch.transpose(t, dim0=1, dim1=2)    # c*h*w     h*w*c
print("t shape:{}\nt_transpose shape: {}".format(t.shape, t_transpose.shape))

t shape:torch.Size([2, 3, 4])
t_transpose shape: torch.Size([2, 4, 3])


### torch.t()

### torch.squeeze() : 压缩长度为1的维度(轴)

dim:   
- None ： 移除所有长度为1的轴;
- 指定维度: 当且仅当该轴长度为1时，可以被移除;

In [21]:
t = torch.rand((1, 2, 3, 1))
t_sq = torch.squeeze(t)
t_0 = torch.squeeze(t, dim=0)
t_1 = torch.squeeze(t, dim=1)
print(t.shape)
print(t_sq.shape)
print(t_0.shape)
print(t_1.shape)

torch.Size([1, 2, 3, 1])
torch.Size([2, 3])
torch.Size([2, 3, 1])
torch.Size([1, 2, 3, 1])


## 张量的运算

In [22]:
t_0 = torch.randn((3, 3))
t_1 = torch.ones_like(t_0)
t_add = torch.add(t_0, 10, t_1)

print("t_0:\n{}\nt_1:\n{}\nt_add_10:\n{}".format(t_0, t_1, t_add))

t_0:
tensor([[-1.3613,  0.2182, -1.3080],
        [ 0.2517,  1.8713, -0.3401],
        [ 0.9449,  0.4791,  0.7199]])
t_1:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t_add_10:
tensor([[ 8.6387, 10.2182,  8.6920],
        [10.2517, 11.8713,  9.6599],
        [10.9449, 10.4791, 10.7199]])


..\torch\csrc\utils\python_arg_parser.cpp:756: UserWarning: This overload of add is deprecated:
	add(Tensor input, Number alpha, Tensor other, *, Tensor out)
Consider using one of the following signatures instead:
	add(Tensor input, Tensor other, *, Number alpha, Tensor out)


In [7]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [9]:
x[1][1]

3